<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;netstandard2.0;net10.0;net9.0;net8.0;net471;net462</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Description>High‑level data access utilities for .NET, providing extensions for DataReader, DataRow, and DataTable, plus lightweight DAL helpers, DbConverter, and IDbContext abstractions. Designed to simplify common database operations and improve consistency across data access layers.</Description>
    <RootNamespace />
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591;NETSDK1233</NoWarn>
    <VersionPrefix>0.7.6</VersionPrefix>
  </PropertyGroup>

  <ItemGroup Condition="'$(NuExt_UseLocalProjects)' != 'true'">
    <PackageReference Include="NuExt.System" Version="0.7.6" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuExt_UseLocalProjects)' == 'true'">
    <ProjectReference Include="..\..\NuExt.System\src\NuExt.System.csproj" />
  </ItemGroup>

</Project>
